
CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers(
	id INT NOT NULL AUTO_INCREMENT,
	burger_name VARCHAR(60) NOT NULL,
	devoured BOOLEAN DEFAULT FALSE,
	date VARCHAR(10) NULL,
	PRIMARY KEY (id)
);